### PR TITLE
Correctly pass 'kind' parameter to FirestoreStore instead of to Firestore

### PR DESCRIPTION
**Pull request by scharan**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] [bug 61](https://github.com/googleapis/nodejs-firestore-session/issues/61)
- [ ] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x ] Appropriate docs were updated (if necessary)

Fixes #<61> 🦕

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
@fhinkel mind taking a look?

**Comment by BenWhitehead** [comment]
@scharan Can you please follow the instructions from CLA bot so we can accept you contribution?

**Comment by scharan** [comment]
@googlebot I signed it!

**Comment by scharan** [comment]
@googlebot I signed it!

**Pull request closed without merging**
